apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: finanse
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      sslmode: disable
    editable: true